name: "CD Azure Container Instances"

on:
  workflow_dispatch:
jobs:

  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ttcnhosting.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    - name: Build and push Docker images
      run: |
        docker build . -t ttcnhosting.azurecr.io/orders-service:latest -t ttcnhosting.azurecr.io/orders-service:${{ github.sha }}
        docker push ttcnhosting.azurecr.io/orders-service:latest 
        docker push ttcnhosting.azurecr.io/orders-service:${{ github.sha }}
      working-directory: ./src/OrdersService
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: 'build'
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: rg-tt-cn-hosting
        dns-name-label: orders-service-${{ github.run_number }}
        image: ttcnhosting.azurecr.io/orders-service:${{ github.sha }}
        registry-login-server: ttcnhosting.azurecr.io
        registry-username: ${{ secrets.ACR_TOKEN_NAME }}
        registry-password: ${{ secrets.ACR_TOKEN_PASSWORD }}
        cpu: 0.5
        memory: 1.5
        ports: 5000
        name: cg-tt-cn-hosting
        location: 'germanywestcentral'
      