name: "CD Azure Kubernetes Service"

on:
  workflow_dispatch:
jobs:

  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ttcnhosting.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    - name: Build and push Docker images
      run: |
        docker build . -t ttcnhosting.azurecr.io/orders-service:latest -t ttcnhosting.azurecr.io/orders-service:${{ github.sha }}
        docker push ttcnhosting.azurecr.io/orders-service:latest 
        docker push ttcnhosting.azurecr.io/orders-service:${{ github.sha }}
      working-directory: ./src/OrdersService
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: 'build'
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/aks-set-context@v3
      name: Set AKS as current context
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: aks-tt-cn-hosting
        resource-group: rg-tt-cn-hosting
    - uses: Azure/k8s-deploy@v1
      name: Deploy Namespace
      with:
        manifests: |
          kubernetes/namespace.yml
    - uses: Azure/k8s-deploy@v1
      name: Deploy to Azure Kubernetes Service
      with:
        namespace: thinktecture-webinar
        manifests: |
          kubernetes/deployment.yml
          kubernetes/service.yml
        images: |
          ttcnhosting.azurecr.io/orders-service:${{ github.sha }}
      