name: "CD Azure App Services (Linux)"

on:
  workflow_dispatch:
jobs:

  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ttcnhosting.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    - name: Build and push Docker images
      run: |
        docker build . -t ttcnhosting.azurecr.io/orders-service:latest -t ttcnhosting.azurecr.io/orders-service:${{ github.sha }}
        docker push ttcnhosting.azurecr.io/orders-service:latest 
        docker push ttcnhosting.azurecr.io/orders-service:${{ github.sha }}
      working-directory: ./src/OrdersService
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: 'build'
    steps:
    - uses: azure/webapps-deploy@v2
      name: Deploy to Azure App Service (Linux)
      with:
        app-name: 'as-tt-cn-hosting-linux-webapp'
        publish-profile: ${{ secrets.LINUX_WEBAPP_PUBLISHING_PROFILE }}
        images: 'ttcnhosting.azurecr.io/orders-service:${{ github.sha }}'
      